config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  get 'hello/index' => 'hello#index'
  get 'chats/:chat_id/likes' => 'likes#create'
  get 'chats/:chat_id/likes/:id' => 'likes#destroy'
  
  resources :chats do
  resources :likes, only: [:create, :destroy]
 end
 resources :users, only: [:show] # ユーザーマイページへのルーティング
 root 'hello#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user

    has_many :likes, dependent: :destroy    
    has_many :liked_users, through: :likes, source: :user

    has_many :chat_tag_relations, dependent: :destroy
    has_many :tags, through: :chat_tag_relations, dependent: :destroy

    

    mount_uploader :image, ImageUploader

    validates :drink, :snack, presence: true
end

app/models/chat_tag_relation.rb
class ChatTagRelation < ApplicationRecord
  belongs_to :chat
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :chat
  belongs_to :user
  validates_uniqueness_of :chat_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :chat_tag_relations, dependent: :destroy
    has_many :chats, through: :chat_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :chats, dependent: :destroy
 has_many :likes, dependent: :destroy
 has_many :liked_chats, through: :likes, source: :chat
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記

 def already_liked?(chat)
  self.likes.exists?(chat_id: chat.id)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def index
    @chats = Chat.all
end

before_action :configure_permitted_parameters, if: :devise_controller?

protected
def configure_permitted_parameters
  # サインアップ時にnameのストロングパラメータを追加
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # アカウント編集の時にnameとprofileのストロングパラメータを追加
  devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
end

def after_sign_in_path_for(resource)
  chats_path # ログイン後にリダイレクトするページを指定
end


end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    # ベースのクエリは全てのチャット
    @chats = Chat.all
    @user = User.all
    # 検索機能
    if params[:search].present?
      @chats = @chats.where("body LIKE ?", "%#{params[:search]}%")
    end

    # お酒検索
    if params[:drink].present?
      @chats = @chats.where("drink LIKE ?", "%#{params[:drink]}%")
    end

    # あて検索
    if params[:snack].present?
      @chats = @chats.where("snack LIKE ?", "%#{params[:snack]}%")
    end
    
    # タグによる絞り込み
    if params[:tag_ids].present?
      @chats = @chats.joins(:tags).where(tags: { id: params[:tag_ids] }).distinct
    end

    # 新しい順にソート
    case params[:sort]
    when 'likes'
      @chats = @chats.left_joins(:likes).group(:id).order('COUNT(likes.id) DESC')
    when 'oldest'
      @chats = @chats.order(created_at: :asc)
    else
      @chats = @chats.order(created_at: :desc) # 新しい順
    end
  end   

  def new
    @chat = Chat.new
  end
  
  def create
    chat = Chat.new(chat_params)
    chat.user_id = current_user.id

    if chat.save
      redirect_to chats_path, notice: "投稿が保存されました"
    else
      render :new
    end
  end
  
  def show
    @chat = Chat.find(params[:id])
  end

  def edit
    @chat = Chat.find(params[:id])
  end

  def update
    chat = Chat.find(params[:id])
    if chat.update(chat_params)
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    chat = Chat.find(params[:id])
    chat.destroy
    redirect_to action: :index
  end

  

  private

  def chat_params
    params.require(:chat).permit(:name, :body, :drink, :snack, :image, tag_ids: [])
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index

    
        # ChatsController の index ロジックをコピー
        @chats = Chat.all
        @user = User.all
        
        # 検索機能
        if params[:search].present?
            @chats = @chats.where("body LIKE ?", "%#{params[:search]}%")
        end
    
        if params[:drink].present?
            @chats = @chats.where("drink LIKE ?", "%#{params[:drink]}%")
        end
    
        if params[:snack].present?
            @chats = @chats.where("snack LIKE ?", "%#{params[:snack]}%")
        end
    
        if params[:tag_ids].present?
            @chats = @chats.joins(:tags).where(tags: { id: params[:tag_ids] }).distinct
        end
    
        case params[:sort]
        when 'likes'
            @chats = @chats.left_joins(:likes).group(:id).order('COUNT(likes.id) DESC')
        when 'oldest'
            @chats = @chats.order(created_at: :asc)
        else
            @chats = @chats.order(created_at: :desc)
        end
        end
    end
    

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(chat_id: params[:chat_id]) 
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(chat_id: params[:chat_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @chats = @user.chats  
        

      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/edit.html.erb
<h3>投稿の編集</h3>

<div class="form-container">
<%= form_with(model: @chat, local: true,) do |f| %>
  <div class="field">
    <%= f.label :drink, "お酒" %>
    <%= f.text_field :drink %>
  </div>

  <div class="field">
    <%= f.label :snack, "あて" %>
    <%= f.text_field :snack %>
  </div>

  <div class="field">
    <%= f.label :body, "詳しく！" %>
    <%= f.text_area :body, size: "60x15" %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %>
    <%= f.file_field :image %>
  </div>
  
  <div class='form-group'>
    <%= f.label :tags, "タグを選択" %>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check'>
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= f.submit "編集する！", class: "btn btn-primary" %>
<% end %>

<%= link_to "Tweet一覧に戻る", chats_path, class: "btn btn-secondary" %>
</div>

app/views/chats/index.html.erb
<!-- ソートオプション -->
<div class="sort-options">
  <%= link_to "新しい順", chats_path(sort: 'newest') %> 
  <%= link_to "古い順", chats_path(sort: 'oldest') %> 
  <%= link_to "いいね順", chats_path(sort: 'likes') %>
</div>

<h2 class="search-title">投稿を検索する</h2>


<%= form_tag({controller: "hello", action: "index"}, method: :get) do %>
  <div class="searchbox">
    <%= text_field_tag :drink, params[:drink], placeholder: "お酒を検索", class: "search-input" %>
    <h4 class="search-separator">×</h4>
    <%= text_field_tag :snack, params[:snack], placeholder: "あてを検索", class: "search-input" %>
  </div>

  <div class="tag-box">
    <% Tag.all.each do |t| %>
      <label class="tag-label">
        <%= check_box_tag 'tag_ids[]', t.id, params[:tag_ids]&.include?(t.id.to_s), class: "tag-checkbox" %>
        <span class="tag-name"><%= t.name %></span>
      </label>
    <% end %>
  </div>

  
  <%= submit_tag '検索', class: "search-button" %>
<% end %>



<div class="chats-container">
  <% @chats.each do |chat| %>
    <%= link_to chat_path(chat.id), class: "chat-item-link" do %>
      <div class="chat-item">
        <h2><%= chat.drink %> ✖️ <%= chat.snack %></h2>

          <% if chat.tags.any? %>
          <p>#
            <% chat.tags.each do |tag| %>
              <span><%= tag.name %></span>
            <% end %>
          </p>
          <% end %>

          <%= image_tag chat.image_url, size: "250x200" if chat.image? %>
          
          

          <p><%= chat.created_at.strftime("%Y年%m月%d日 %H:%M") %></p>
          <p><%= chat.user.name %></p>

          <div class="buttons">
            
            <% if user_signed_in? && current_user.id == chat.user_id %>
              <%= link_to "編集する", edit_chat_path(chat.id), class: "btn btn-primary4" %>
              <%= button_to "削除する", chat_path(chat.id), method: :delete, class: "btn btn-danger1" %>
            <% end %>

            <!-- いいね機能 -->
            
              <% if current_user.liked_chats.include?(chat) %>
                <%= button_to 'いいねを取り消す', chat_like_path(chat, current_user.likes.find_by(chat: chat)), method: :delete, class: "btn btn-warning1" %>
              <% else %>
                <%= button_to 'いいね', chat_likes_path(chat), method: :post, class: "btn btn-success1" %>
              <% end %>
            
          </div>
        <p>いいねの数: <%= chat.likes.count %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/chats/new.html.erb
<h3>新規投稿</h3>



<div class="form-container">
<%= form_with(model: @chat, local: true, multipart: true) do |f| %>
  <!-- お酒とアテのコンテナ -->
  <div class="drink-snack-container">
    <!-- お酒のフィールド -->
    <div class="field drink-field">
      <%= f.label :drink, "お酒" %>
      <%= f.text_field :drink, class: 'form-control drink-input' %>
    </div>
    
    <!-- "×" 記号 -->
    <div class="x-symbol">
      ×
    </div>
    
    <!-- アテのフィールド -->
    <div class="field snack-field">
      <%= f.label :snack, "あて" %>
      <%= f.text_field :snack, class: 'form-control snack-input' %>
    </div>
  </div>

  <!-- 投稿内容 -->
  <div class="field">
    <%= f.label :body, "詳しく！" %>
    <%= f.text_area :body, size: "60x15", class: 'form-control' %>
  </div>

  <!-- 画像アップロード -->
  <div class="field">
    <%= f.label :image, "画像" %>
    <%= f.file_field :image, class: 'form-control-file' %>
  </div>
  
  <!-- タグ選択 -->
  <div class='form-group'>
    <%= f.label :tags, "タグを選択" %>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check form-check-inline'>
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>

  <!-- 送信ボタン -->
  <%= f.submit "投稿する", class: "btn btn-3 btn-block" %>
<% end %>

<%= link_to "投稿一覧に戻る", chats_path, class: "btn btn-secondary btn-block mt-3" %>
</div>

app/views/chats/show.html.erb
<div class="chat-detail-container">
  <div class="chat-item-detail">
      
    <h2><%= @chat.drink %> ✖️ <%= @chat.snack %></h2>
    <div class="name-and-tag">
      <p>投稿者: <%= @chat.user.name %></p> 
      <div class="chat-tags">
        <% @chat.tags.each do |tag| %>
          <span><%= tag.name %></span>
        <% end %>
      </div>
    </div>

    <p><%= @chat.body %></p>
    <p><%= @chat.created_at.strftime("%Y年%m月%d日 %H:%M") %></p>

    <% if @chat.image? %>
      <p><strong>画像：</strong></p>
      <%= image_tag @chat.image.url, alt: "投稿画像" %>
    <% end %>
    
    <%= link_to "Tweet一覧に戻る", chats_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/hello/index.html.erb
<h2 class="search-title">投稿を検索する</h2>

<%= form_tag({controller: "hello", action: "index"}, method: :get) do %>
  <div class="searchbox">
    <%= text_field_tag :drink, params[:drink], placeholder: "お酒を検索", class: "search-input" %>
    <h4 class="search-separator">×</h4>
    <%= text_field_tag :snack, params[:snack], placeholder: "あてを検索", class: "search-input" %>
  </div>

  <div class="tag-box">
    <% Tag.all.each do |t| %>
      <label class="tag-label">
        <%= check_box_tag 'tag_ids[]', t.id, params[:tag_ids]&.include?(t.id.to_s), class: "tag-checkbox" %>
        <span class="tag-name"><%= t.name %></span>
      </label>
    <% end %>
  </div>

  
  <%= submit_tag '検索', class: "search-button" %>
<% end %>

<div class="chats-container">
  <% @chats.each do |chat| %>
    <div class="chat-item">
      <h2><%= chat.drink %> ✖️ <%= chat.snack %></h2>

      <% if chat.tags.any? %>
        <p>
          <% chat.tags.each do |tag| %>
            <span><%= tag.name %></span>
          <% end %>
        </p>
      <% end %>

      <%= image_tag chat.image_url, size: "250x200" if chat.image? %>

      <p><%= chat.created_at.strftime("%Y年%m月%d日 %H:%M") %></p>
      <p><%= chat.user.name %></p>
      <%= link_to "詳細へ", chat_path(chat.id), class: "focus" %>
      

      <p>いいねの数: <%= chat.likes.count %></p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>お酒×</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="<%= 'random-header' if controller_name == 'hello' && action_name == 'index' %>">
      <% if controller_name == 'hello' && action_name == 'index' %>
      <!-- hello/index ページ専用のヘッダー -->
      <div class="left-section">
      </div>

      <div class="right-section">
        <div class="header-list">
          <ul>
            <li>
            <% if user_signed_in? %>
              <%= link_to 'ログイン', chats_path %>
            <% else %>
              <%= link_to 'ログイン', new_user_session_path %>
            <% end %>
            </li>
            <li><%= link_to '新規登録', new_user_registration_path %></li>
          </ul>
        </div>
      </div>

      <div class="header-logo">
        <%= image_tag 'logo2.png', alt: 'サイトのロゴ' %>
        <p class="logo-description">お酒好きのための情報共有サイト</p>
      </div>

      <% else %>
        <!-- 通常のヘッダー -->
        <div class="header-title">
          <div class="logo">
            <%= image_tag 'logo2.png', alt: 'サイトロゴ' %> <!-- 通常のロゴ -->
            <p class="logo-tagline">お酒好きの情報共有サイト</p> <!-- 説明文 -->
          </div>
        </div>

        <div class="header-list">
          <ul>
            <li><%= link_to "ホーム", chats_path %></li>
            <li><%= link_to "共有する", new_chat_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "マイページへ", user_path(current_user.id) %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'ログイン', new_user_session_path %></li>
              <li><%= link_to '新規登録', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </header>

    <main>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>



<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="user-profile">
  <h2 class="user-name"><%= @user.name %> さんのマイページ</h2>
  <div class="user-info">
    
    <p><strong>プロフィール:</strong> <%= @user.profile %></p>
  </div>

  <% if current_user.id == @user.id %>
    <div class="edit-profile">
      <%= link_to "アカウントを編集する", edit_user_registration_path, class: "btn btn-primary" %>
    </div>
  <% end %>

  <h2 class="section-title">投稿一覧</h2>
  <% if @chats.any? %>
    <div class="chats-container">
      <% @chats.each do |chat| %>
        <div class="chat-item">
          <h3><%= chat.drink %> ✖️ <%= chat.snack %></h3>
          <p class="chat-user"><%= @user.name %></p>
          <% if chat.tags.any? %>
            <p class="chat-tags">#
              <% chat.tags.each do |tag| %>
                <span class="chat-tag"><%= tag.name %></span>
              <% end %>
            </p>
          <% end %>

          <%= image_tag chat.image_url, size: "250x200", class: "chat-image" if chat.image? %>
          
          <p class="chat-body"><%= chat.body %></p>
          <p class="chat-date"><%= chat.created_at.strftime("%Y年%m月%d日 %H:%M") %></p>
          <p class="chat-user"><%= @user.name %></p>
          
          
          
          <% if user_signed_in? && current_user.id == chat.user_id %>
            <%= button_to "編集する", edit_chat_path(chat.id), class: "btn btn-primary2" %>
            <%= button_to "削除する", chat_path(chat.id), method: :delete, class: "btn btn-danger" %>
          <% end %>

          <!-- いいね機能 -->
          <% if user_signed_in? %>
            <% if current_user.liked_chats.include?(chat) %>
              <%= button_to 'いいねを取り消す', chat_like_path(chat, current_user.likes.find_by(chat: chat)), method: :delete, class: "btn btn-warning" %>
            <% else %>
              <%= button_to 'いいね', chat_likes_path(chat), method: :post, class: "btn btn-success" %>
            <% end %>
          <% end %>

          <p class="like-count">いいねの数: <%= chat.likes.count %></p>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>まだ投稿はありません。</p>
  <% end %>

  <h2 class="section-title">いいねした投稿</h2>
  <% if @user.liked_chats.any? %>
    <div class="liked-chats-container">
      <% @user.liked_chats.each do |t| %>
        <div class="liked-chat-item">
          <h3><%= t.drink %> ✖️ <%= t.snack %></h3>
          <p><%= t.body %></p>
          <%= link_to "詳細へ", chat_path(t.id), class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>いいねした投稿はまだありません。</p>
  <% end %>

  <%= link_to "Tweet一覧に戻る", chats_path, class: "btn btn-secondary" %>
</div>